default: &default
  timeout: 5000
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  username: postgres
test:
  <<: *default
production:
  <<: *default
  database: d8rpt06fuskpip
  username: iuosnvcombkimq
  host: localhost
